### ISSUE TITLE
Unable to remove trigger

### ISSUE THREAD

**Issue by tomsawdayee** [iftahbe/quartznet-RavenDB#3]
When I call UnscheduleJob, the trigger for the selected job is supposed to be removed.

As it seems, in file RavenJobStore.cs, function RemoveTrigger is supposed to remove the trigger. Currently, it does not seem to remove the trigger. It is looking for triggers, but when it finds any, it does not do anything. Is there anything you can do to resolve this?

Thanks,

Tom

**Comment by iftahbe** [comment]
Yes it's a bug, I'll fix it.

**Comment by tomsawdayee** [comment]
Wonderful. Looking forward

Thanks

**Comment by iftahbe** [comment]
I tested it, UnscheduleJob() works now. 
I will also update the nugget package and add a test for that soon.

**Comment by tomsawdayee** [comment]
Great. I'm waiting for the package :)

**Comment by iftahbe** [comment]
Package 1.0.3 published. Thanks...
